apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: client
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: client
    spec:
      containers:
      - args:
        - npm
        - run
        - start
        env:
        - name: MYSQL_DATABASE
          value: handf
        - name: MYSQL_PASSWORD
          value: topher123
        - name: MYSQL_ROOT_PASSWORD
          value: topher123
        - name: MYSQL_USER
          value: root
        - name: NODE_PATH
          value: src
        - name: REACT_APP_SERVER_PORT
          value: "3000"
        image: client
        imagePullPolicy: ""
        name: client
        ports:
        - containerPort: 3000
        resources: {}
        stdin: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
