version: "3.5"

services:
  mysql:
    container_name: mysql
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: topher123
      MYSQL_PASSWORD: topher123
      MYSQL_DATABASE: handf
    networks:
      - main
    ports:
      - 3306:3306
    restart: always
    volumes:
      - handf-data:/var/lib/mysql
      - ./handf-db/createTables.sql:/docker-entrypoint-initdb.d/1.sql

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    links:
      - mysql:mysql
    ports:
      - 8080:80
    restart: always

  redis:
    container_name: redis
    image: redis:latest
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    networks:
      - main
    ports:
      - 6379:6379

  server:
    container_name: server
    build: ./server
    depends_on:
      - mysql
      - redis
    expose:
      - 3010
    environment:
      PORT: 3010
      DB_USER: root
      DB_HOST: mysql
      DB_PASSWORD: topher123
      DB_DATABASE: handf
      REDIS: redis
    ports:
      - 3010:3010
    networks:
      - main
    volumes:
      - ./client/build:/client/build
    links:
      - mysql:mysql
      - redis:redis
    command: node index.js
    restart: always

#  client:
#    container_name: client
#    build:
#      context: client
#      dockerfile: ./deploy/Dockerfile
#    environment:
#      REACT_APP_SERVER_PORT: 3010
#      REACT_APP_SERVER_HOST: localhost
#      NODE_PATH: src
#    ports:
#      - 3000:3000
#    volumes:
#      - ./handf-client/src:/app/src
#    restart: always
#    stdin_open: true

  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    image: postgres:9.6
    container_name: kong-database
    restart: on-failure
    networks:
      - kong-net
    volumes:
      - kong_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: ${KONG_PG_PASSWORD:-kong}
      POSTGRES_DB: kong
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "kong" ]
      interval: 30s
      timeout: 30s
      retries: 3

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    image: ${KONG_DOCKER_TAG:-kong:latest}
    command: kong migrations bootstrap
    networks:
      - kong-net
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-kong}
    depends_on:
      - kong-database

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    container_name: kong
    image: ${KONG_DOCKER_TAG:-kong:latest}
    restart: on-failure
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-kong}
      KONG_PROXY_LISTEN: 0.0.0.0:80
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      - kong-database
    volumes:
      - ./go-pluginserver/go-pluginserver:/usr/local/bin/go-pluginserver
      - ./plugins:/usr/local/kong/plugins/
      - ./go-plugins:/usr/local/kong/go_plugins/
      - ./kong.conf:/etc/kong/kong.conf
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"

  #######################################
  # Konga database prepare
  #######################################
  konga-prepare:
    image: pantsel/konga:latest
    command: "-c prepare -a postgres -u postgresql://kong:${KONG_PG_PASSWORD:-kong}@kong-database:5432/konga"
    networks:
      - kong-net
    restart: on-failure
    depends_on:
      - kong-database

  #######################################
  # Konga: Kong GUI
  #######################################
  konga:
    image: pantsel/konga:latest
    restart: always
    networks:
      - kong-net
    environment:
      DB_ADAPTER: postgres
      DB_URI: postgresql://kong:${KONG_PG_PASSWORD:-kong}@kong-database:5432/konga
      NODE_ENV: production
    depends_on:
      - kong-database
    ports:
      - "1337:1337"

volumes:
  handf-data:
  kong_data: {}

networks:
  kong-net:
  main:
