version:'3'
services:
  frontend:
    build: ./client
    image: "reactapp:1.0.0"
    container_name: frontend
    networks:
      - hand-and-foot
  backend:
    build: ./server
    image: "expressapp:1.0.0"
    container_name: backend
    restart: always
    depends_on:
      - mysql
      - redis
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: topher123
      DB_DATABASE: handf
      REDIS: redis
    networks:
      - hand-and-foot
  redis:
    image: "redis:alpine"
    container_name: redis
    networks:
      - hand-and-foot
  mysql:
    build: ./database
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: topher123
    volumes:
      - ./db_data:/var/lib/mysql:rw
      - ./database/createTables.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - hand-and-foot
  revproxy:
    build: ./proxy
    image: "reverseproxy:1.0.0"
    networks:
      - hand-and-foot
    ports:
      - "80:80"
networks:
  hand-and-foot:
volumes:
  db_data:
