apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: server
    spec:
      containers:
      - args:
        - node
        - index.js
        env:
        - name: DB_DATABASE
          value: handf
        - name: DB_HOST
          value: mysql
        - name: DB_PASSWORD
          value: topher123
        - name: DB_USER
          value: root
        - name: PORT
          value: "3010"
        - name: REDIS
          value: redis://redis:6379
        image: server
        imagePullPolicy: ""
        name: server
        ports:
        - containerPort: 3010
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
