version: '3.8'
services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
  mysql:
    build: .
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: topher123
    volumes:
      - db_data:/var/lib/mysql:rw
      - ./createTables.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
volumes:
  db_data:
